services:
  web:
    build: .
    container_name: customlab_api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - customlab_network
    restart: unless-stopped

networks:
  customlab_network:
    external: true
